### ISSUE TITLE
Single responsibility 

### ISSUE THREAD

**Issue by fclante** [ErikAndersen81/DopeWars#1]
One class per file is better we can group them into folders

**Comment by ErikAndersen81** [comment]
Når jeg lægger en super class sammen med de classes som arver fra dem i et
modul, bliver det lettere at importere dem senere.
Eg:
from npc import *

Vs
from dealer import Dealer
from thug import Thug
Etc..

Den 6. aug. 2016 11.22 PM skrev "Frey Clante" <notifications@github.com>:

**Comment by ErikAndersen81** [comment]
For læsbarhedens skyld kan man også importere med namespace. (The pythonic
way..)
eg:
import npc

thug=npc.Thug()

Den 7. aug. 2016 9.47 AM skrev "Erik Andersen" <jensenerik81@gmail.com>:

**Comment by ErikAndersen81** [comment]
Ok så, jeg forsøger at lave en python package istedet, så hver class får
sin egen fil.

Den 7. aug. 2016 9.51 AM skrev "Erik Andersen" <jensenerik81@gmail.com>:
